"""inserindo o campo user_id no teams

Revision ID: 39bd75ad7f5e
Revises: edd7468a663a
Create Date: 2025-05-22 20:50:58.931308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bd75ad7f5e'
down_revision: Union[str, None] = 'edd7468a663a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'user_id')
    # ### end Alembic commands ###
