"""renomeando coluna <user_id> para <current_user_id>

Revision ID: b8839391ece6
Revises: 39bd75ad7f5e
Create Date: 2025-05-22 21:07:14.384638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8839391ece6'
down_revision: Union[str, None] = '39bd75ad7f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('current_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('teams_user_id_fkey', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['current_user_id'], ['id'])
    op.drop_column('teams', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('teams_user_id_fkey', 'teams', 'users', ['user_id'], ['id'])
    op.drop_column('teams', 'current_user_id')
    # ### end Alembic commands ###
