"""ajuste nos campos do modelo Sprint

Revision ID: cdc49c032762
Revises: e7f562142636
Create Date: 2025-06-26 17:23:09.823651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc49c032762'
down_revision: Union[str, None] = 'e7f562142636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('sprints', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('sprints', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('sprints', sa.Column('description', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sprints', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.drop_column('sprints', 'description')
    op.drop_column('sprints', 'end_date')
    op.drop_column('sprints', 'start_date')
    op.drop_column('sprints', 'project_id')
    # ### end Alembic commands ###
