"""ajuste nos campos do modelo Sprint

Revision ID: e7f562142636
Revises: 78ac2b231d06
Create Date: 2025-06-26 15:28:09.250786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f562142636'
down_revision: Union[str, None] = '78ac2b231d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('sprint_name', sa.String(), nullable=False))
    op.drop_column('sprints', 'project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sprints', 'sprint_name')
    # ### end Alembic commands ###
