"""Remove user_list from teams

Revision ID: edd7468a663a
Revises: e7b1fd33a602
Create Date: 2025-05-18 17:44:14.114353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd7468a663a'
down_revision: Union[str, None] = 'e7b1fd33a602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_user_list_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'user_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('user_list', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_user_list_fkey', 'teams', 'users', ['user_list'], ['username'])
    # ### end Alembic commands ###
